apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: second-rs
spec:
  replicas: 2
  selector:
    matchLabels:
            env: dev
  template:
    metadata:
      labels:
              env: dev
    spec:
      containers:
      - name: nginx
        image: nginx

